[package]
name = "fusb302b"
version = "0.0.1"
edition = "2024"
description = "FUSB302B driver for `usb-pd` library."
documentation = "https://docs.rs/fusb302b"
repository = "https://github.com/fmckeogh/usb-pd-rs"
homepage = "https://github.com/fmckeogh/usb-pd-rs"
license = "MIT"
keywords = ["nostd", "usb-pd", "driver", "embedded", "fusb302b"]

[lib]
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors
test = false

[dependencies]
byteorder = { version = "1.5", default-features = false }
embedded-hal-async = "1.0"
heapless = { version = "0.8", features = ["defmt-03"] }
defmt = "1.0"
paste = "1.0"
proc-bitfield = "0.5"
embassy-time = "0.4"

usb-pd = { path = "../usb-pd" }
